# Generated by Django 4.2.23 on 2025-11-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.CASCADE, to='users.user'),
        ),
    ]
