# Generated by Django 5.2.8 on 2025-11-16 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20251115_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='source',
        ),
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alert',
            name='incident_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alerts.location'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('resolved', 'Resolved')], default='active', max_length=10),
        ),
    ]
